namespace ET.Sms.PostaGuvercini.Constants
{
    public static class ApiResponseConstants
    {
        public static Dictionary<string, string> ErrorCodes = new Dictionary<string, string>()
        {
            { "-1001", "Kullanıcı adı geçersiz" },
            { "-1002", "Şifre geçersiz" },
            { "-1003", "GSM numarası geçersiz" },
            { "-1004", "Text/Ringtone/Ologo/SendBin parametresi geçersiz" },
            { "-1005", "Message_id  geçersiz" },
            { "-2001", "API Hatası" },
            { "-2002", "Veritabanı Hatası" },
            { "0", "Hata yok" },
            { "10", "Kullanıcı adı veya şifre yanlış" },
            { "20", "Yeterli krediniz yok" },
            { "30", "Operator logo kodu yanlış" },
            { "31", "Operator logo sahibi değilsiniz" },
            { "32", "Operator logo değil" },
            { "40", "Ringtone kodu yanlış" },
            { "41", "Ringtone sahibi değilsiniz" },
            { "42", "Ringtone değil" },
            { "50", "Binary SMS kodu yanlış" },
            { "51", "Binary SMS sahibi değilsiniz" },
        };

        public static Dictionary<string, string> StatusCodes = new Dictionary<string, string>()
        {
            { "110", "Gönderilmeyi bekliyor" },
            { "120", "Gönderilmeyi bekliyor" },
            { "200", "Gönderiliyor" },
            { "300", "Gönderildi" },
            { "400", "Ulaştı" },
            { "401", "Alıcıya gönderilecek" },
            { "402", "Ulaşmadı" },
            { "403", "Ulaşmadı (Zaman Aşımı)" },
            { "404", "Ulaşmadı (Bilinmeyen Hat)" },
            { "405", "Ulaşmadı (Sistem Hatası)" },
            { "406", "Ulaşmadı (SMS’e Kapalı)" },
            { "407", "Ulaşmadı (Cihaz Hatası)" },
            { "408", "Ulaşmadı (Cihaza Ulaşılamadı)" },
            { "409", "Ulaşmadı (Operatör kısıtlama durumu)" },
            { "410", "Bilinmiyor" },
            { "411", "Ulaşmadı (Cihaz hafızası dolu)" },
            { "412", "Ulaşmadı (Ulaşılamayan abone)" },
            { "413", "Ulaşmadı (Abone profilindeki yetkilendirme yetersiz)" },
            { "414", "Ulaşmadı (Bilinmeyen Abone Veya Yetersiz Kontor)" },
            { "420", "Bilinmiyor" },
            { "421", "Ulaşmadı (IYS Sistem Hatası)" },
            { "422", "Ulaşmadı (IYS Parametre Hatası)" },
            { "423", "Ulaşmadı (IYS Tanım Hatası)" },
            { "424", "Ulaşmadı (IYS Onaylı Listede Yok)" },
            { "425", "Ulaşmadı (IYS Geçersiz Numara)" },
            { "426", "Ulaşmadı (IYS Bilinmeyen Hata Kodu)" },
            { "-20", "Bilinmiyor" },
            { "-201", "Silindi (Geçersiz cep no.)" },
            { "-202", "Silindi (İçerik tekrarı)" },
            { "-203", "Silindi (Geçersiz son gönderim tarihi)" },
            { "-205", "Silindi (Mesaj çok uzun)" },
            { "-207", "Silindi (Mesaj merkezi reddetti)" },
            { "-208", "Silindi (Mesaj merkezi reddetti, yetersiz kredi)" },
            { "-210", "Silindi (Zaman aşımı)" },
            { "-211", "Silindi (TCNO bulunamadı)" },
            { "-212", "Silindi (Birden çok TCNO bulundu)" },
            { "-213", "Silindi (TCNO geçersiz)" },
            { "-214", "Silindi (VergiNo bulunamadı)" },
            { "-220", "Silindi (Yetersiz kredi zaman aşımı)" },
            { "-222", "Ulaşmadı (Abone bloke isteği)" },
            { "-223", "Ulaşmadı (Gönderim Kısıtlaması)" },
            { "-241", "Silindi (Alıcı RET İşlemi)" },
            { "-242", "Silindi (İzinli Paz, Kara Liste)" },
            { "-243", "Silindi (İzinli Paz, Liste Dışı)" },
            { "-250", "Silindi (Müşteri tarafından)" },
            { "-260", "Silindi (Fatura borcu)" },
            { "-261", "Silindi (Sanal No Blokeli)" },
            { "-262", "Silindi (Operator Kodsuz Blokeli Alfanumerik)" },
            { "-263", "Silindi (İçerik Filtre)" },
            { "-270", "Silindi (Gsmnı Yönlendirilemedi)" },
            { "-441", "Alfanumerik Hatası" },
            { "-426", "Basit Bir Gönderim Hatası" },
            { "-462", "Fatura Borcu" },
            { "-200", "Tanım Hatası" },
            { "-444", "Abone Bloke İsteği" },
            { "-14241", "Kredisi Yok" },
            { "-447", "TR gönderimlerde 268 karakterden daha uzun gönderilemez" },
            { "-470", "TC kimlik numaraya ait gsm no bulunamadı" },
            { "-471", "Bir TC Kimlik No''ya karşılık birden fazla msisdn bulundu" },
            { "-475", "Geçersiz TC Kimlik No" },
            { "-3000", "Veri bulunamadı" },
            { "-3001", "Firmanın TC Kimlik No ise SMS gönderim yetkisi bulunmuyor." },
            { "-3010", "TC kimlik No ile SMS gönderilirken sadece bir tane içerik gönderilebilir." },
            { "-3099", "TC Kimlik No kontrolü yapan web servisten hata döndü." },
            { "-10001", "SanalNo bugün aktiflenmiş, kredi yüklemesi mevcut değil." },
            { "-2478", "Vergi numarasına ait gsm no bulunamadı" },
        };
    }
}
